[package]
name = "fastrie"
description = "Memory-packed tries, buildable at compile time"
license = "MIT"
homepage = "https://github.com/wilsonzlin/fastrie"
version = "0.0.1"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
